GO

CREATE TABLE [EDNF_Poll_Options](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](200) NULL,
	[TopicID] [int] NOT NULL DEFAULT(0),
	[isChecked] [bit] NOT NULL DEFAULT(0),
	[SubmitNum] [int] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_EDNF_Poll_Options] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO