GO

CREATE TABLE [EDNF_Account_RolePermissionsAction](
	[ARPAID] uniqueidentifier NOT NULL,
	[ARPID] uniqueidentifier NOT NULL,
	[ActionCode] [varchar](100) NOT NULL,
 CONSTRAINT [PK_EDNF_Account_RolePermissionsAction] PRIMARY KEY CLUSTERED 
(
	[ARPAID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

