GO

CREATE TABLE [EDNF_Poll_Forms](
	[FormID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[IsActive] [bit] NOT NULL DEFAULT(0),
	[Description] [varchar](300) NULL,
 CONSTRAINT [PK_EDNF_Poll_Forms] PRIMARY KEY NONCLUSTERED 
(
	[FormID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO